cd: updated job dependencies

diff --git a/.ado/deploy_standard.yaml b/.ado/deploy_standard.yaml
--- a/.ado/deploy_standard.yaml
+++ b/.ado/deploy_standard.yaml
@@ -19,6 +19,10 @@ variables:
 
 jobs:
   - job: deploy-hub-network
+    displayName: Deploy 02 Hub Network
+    variables: 
+      - name: workingDirectory
+        value:  "Scenarios/ASA-Secure-Baseline/Terraform/02-Hub-Network"
     pool: 
       vmImage: 'ubuntu-latest'
 
@@ -26,52 +30,68 @@ jobs:
       - checkout: self
       - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
         displayName: Install Terraform
-      - task: AzureCLI@1
+      - task: AzureCLI@2
         displayName: Terraform credentials
         inputs:
-          azureSubscription: ${{ parameters.TerraformEnvironmentServiceConnection }}
+          azureSubscription: $(azureServiceConnection)
           scriptLocation: inlineScript
+          scriptType: ps
           inlineScript: |
             set -eu
-            echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$()"
-            echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$()"
+            echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(armClientId)"
+            echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$(armClientSecret)"
             echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(subscriptionId)"
             echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(tenantId)"
           addSpnToEnvironment: true
 
-      - task: AzureCLI@1
+      - task: AzureCLI@2
         displayName: Terraform init
         inputs:
-          azureSubscription: ${{ parameters.TerraformBackendServiceConnection }}
+          azureSubscription: $(azureServiceConnection)
           scriptLocation: inlineScript
+          scriptType: ps
           inlineScript: |
             set -eux  # fail on error
             terraform init \
-              -backend-config=storage_account_name=$() \
-              -backend-config=container_name=$() \
-              -backend-config=key=$().tfstate \
-              -backend-config=resource_group_name=$()
-          workingDirectory: $()
+              -backend-config=storage_account_name=$(stateStorageAccountName) \
+              -backend-config=container_name=$(stateStorageContainerName) \
+              -backend-config=key=hub-network.tfstate \
+              -backend-config=resource_group_name=$(terraformStateRg)
+          workingDirectory: $(workingDirectory)
           addSpnToEnvironment: true
-      - task: AzureCLI@1
+      - task: AzureCLI@2
         displayName: Terraform plan
         inputs:
-          azureSubscription: ${{ parameters.TerraformBackendServiceConnection }}
+          azureSubscription: $(azureServiceConnection)
           scriptLocation: inlineScript
+          scriptType: ps
           inlineScript: |
             set -eux  # fail on error
             terraform plan -out my.plan \
-              -var="state_sa_rg=$()" \
-              -var="state_sa_name=$()" \
-              -var="state_sa_container_name=$()" \
-              -var="location=$()" \
-              -var="name_prefix=$()" \
-              -var="environment=$()" \
-              -var="SPRINGAPPS_SPN_OBJECT_ID=$()"
-          workingDirectory: $()
+              -var="state_sa_rg=$(terraformStateRg)" \
+              -var="state_sa_name=$(stateStorageAccountName)" \
+              -var="state_sa_container_name=$(stateStorageContainerName)" \
+              -var="location=$(region)" \
+              -var="name_prefix=$(namePrefix)" \
+              -var="environment=$(environment)" \
+              -var="SPRINGAPPS_SPN_OBJECT_ID=$(springAppsSpnObjectId)"
+          workingDirectory: $(workingDirectory)
+          addSpnToEnvironment: true
+      - task: AzureCLI@2
+        displayName: Terraform apply
+        inputs:
+          azureSubscription: $(azureServiceConnection)
+          scriptLocation: inlineScript
+          scriptType: ps
+          inlineScript: |
+            set -eux  # fail on error
+            terraform apply my.plan
+          workingDirectory: $(workingDirectory)
           addSpnToEnvironment: true
 
   - job: deploy-spoke-network
+    displayName: Deploy 03 LZ Network
+    dependsOn: [deploy-hub-network]
     pool: 
       vmImage: 'ubuntu-latest'
 
@@ -79,6 +99,8 @@ jobs:
       - checkout: self
 
   - job: deploy-shared-resources
+    displayName: Deploy 04 LZ Shared Resources
+    dependsOn: [deploy-spoke-network]
     pool: 
       vmImage: 'ubuntu-latest'
 
@@ -86,6 +108,8 @@ jobs:
       - checkout: self
 
   - job: deploy-hub-firewall
+    displayName: Deploy 05 Hub Firewall
+    dependsOn: [deploy-shared-resources, deploy-hub-network]
     pool: 
       vmImage: 'ubuntu-latest'
 
@@ -93,6 +117,8 @@ jobs:
       - checkout: self
 
   - job: deploy-standard-sa
+    displayName: Deploy 06 LZ Spring Apps Standard
+    dependsOn: [deploy-hub-network, deploy-shared-resources, deploy-hub-firewall]
     pool: 
       vmImage: 'ubuntu-latest'
 
@@ -100,13 +126,17 @@ jobs:
       - checkout: self
 
   - job: deploy-pet-clinic-infra
+    displayName: Deploy Pet Clinic Infrastructure
+    dependsOn: [deploy-spoke-network, deploy-shared-resources, deploy-standard-sa]
     pool: 
       vmImage: 'ubuntu-latest'
 
     steps:
       - checkout: self
 
-  - job: deploy-and-deploy-pet-clinic-ms
+  - job: build-and-deploy-pet-clinic-ms
+    displayName: Build and Deploy Pet Clinic Microservices
+    dependsOn: [deploy-pet-clinic-infra, deploy-standard-sa ]
     pool: 
       vmImage: 'ubuntu-latest'
 
@@ -114,13 +144,17 @@ jobs:
       - checkout: self
 
   - job: destroy-pet-clinic-infra
+    displayName: Destroy Pet Clinic Infrastructure
+    dependsOn: [deploy-spoke-network, deploy-shared-resources, deploy-shared-resources, deploy-pet-clinic-infra, build-and-deploy-pet-clinic-ms]
     pool: 
       vmImage: 'ubuntu-latest'
 
     steps:
       - checkout: self
 
-  - job: destroy-spoke-infra
+  - job: destroy-spring-apps-standard
+    displayName: Destroy 06 LZ Spring Apps Standard
+    dependsOn: [destroy-pet-clinic-infra,  deploy-standard-sa]
     pool: 
       vmImage: 'ubuntu-latest'
 
@@ -128,6 +162,8 @@ jobs:
       - checkout: self
 
   - job: destroy-hub-firewall
+    displayName: Destroy 05 Hub Firewall
+    dependsOn: [destroy-spring-apps-standard]
     pool: 
       vmImage: 'ubuntu-latest'
 
@@ -135,6 +171,8 @@ jobs:
       - checkout: self
 
   - job: destroy-shared-resources
+    displayName: Destroy 04 LZ Shared Resources
+    dependsOn: [destroy-hub-firewall]
     pool: 
       vmImage: 'ubuntu-latest'
 
@@ -142,6 +180,8 @@ jobs:
       - checkout: self
 
   - job: destroy-spoke-network
+    displayName: Destroy 03 LZ Network
+    dependsOn: [destroy-shared-resources]
     pool: 
       vmImage: 'ubuntu-latest'
 
@@ -149,6 +189,8 @@ jobs:
       - checkout: self
 
   - job: destroy-hub-network
+    displayName: Destroy 02 Hub Network
+    dependsOn: [destroy-spoke-network]
     pool: 
       vmImage: 'ubuntu-latest'
 
